version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - echo ECR_REPOSITORY=$ECR_REPOSITORY
      - echo trigger build tag 9
      #      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY)
      - PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo $PASSWORD | docker login --username AWS --password-stdin $ECR_REPOSITORY

  build:
    commands:
      - echo Building and Starting Docker containers...
#      - docker-compose up -d
      - docker build -t aplt_notes .
      - docker tag aplt_notes:latest $ECR_REPOSITORY:latest

  post_build:
    commands:
#      - echo Running tests...
#      - docker-compose exec app npm run test
      - echo Pushing Docker image to ECR...
      - echo $ECR_REPOSITORY
      - docker push $ECR_REPOSITORY:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ApltNotes","imageUri":"%s/aplt_notes:latest"}]' $ECR_REPOSITORY > imagedefinitions.json
#      - echo Stopping Docker containers...
#      - docker-compose down

artifacts:
  files: imagedefinitions.json
