version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    image: aplt_notes
    ports:
#      - test
      - "80:80"
    environment:
      - ENVIRONMENT=DEV
      - TOKEN_SECRET=APLT-NOTE-SECRET
      - PORT=80
    depends_on:
      - db
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: aplt-notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

